export const authors = [
  {
    name: "Daniel Tiernan",
    username: "danieltiernan",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
    biography:
      "Daniel Tiernan is an acclaimed author, known for his gripping psychological thrillers that captivate readers worldwide.",
    birthDate: "1975-06-15",
    birthPlace: "Los Angeles, USA",
    nationality: "American",
    famousWork: "The Mind's Edge",
    awards: [{ awardName: "Best Mystery Novel", year: 2019 }],
    booksWrittenIds: ["670015d5acba0ce3c21a3b1b"],
    bestAuthor: false,
    socialLinks: {
      twitter: "https://twitter.com/DanielTiernan",
      facebook: "https://facebook.com/DanielTiernan",
      website: "https://danieltiernan.com",
    },
    totalBooksSold: 500000,
    followers: [],
    isFeatured: false,
    authorQuotes: [
      "Every mystery is a journey into the unknown.",
      "The truth hides in the shadows.",
    ],
  },
  {
    name: "Khari Gordon",
    username: "kharigordon",
    image: "https://randomuser.me/api/portraits/men/12.jpg",
    biography:
      "Khari Gordon, a celebrated author of science fiction, is known for pushing the boundaries of imagination.",
    birthDate: "1982-09-30",
    birthPlace: "Johannesburg, South Africa",
    nationality: "South African",
    famousWork: "Echoes of Tomorrow",
    awards: [{ awardName: "Sci-Fi Author of the Year", year: 2022 }],
    booksWrittenIds: ["670015d5acba0ce3c21a3b1c"],
    bestAuthor: false,
    socialLinks: {
      twitter: "https://twitter.com/KhariGordon",
      facebook: "https://facebook.com/KhariGordon",
      website: "https://kharigordon.com",
    },
    totalBooksSold: 320000,
    followers: [],
    isFeatured: false,
    authorQuotes: [
      "The future is only limited by our imagination.",
      "Science fiction is the blueprint of tomorrow.",
    ],
  },
  {
    name: "Davis Moore",
    username: "davismoore",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
    biography:
      "Davis Moore is an award-winning author whose historical fiction has enchanted readers across the globe.",
    birthDate: "1970-02-19",
    birthPlace: "London, UK",
    nationality: "British",
    famousWork: "The Silent War",
    awards: [{ awardName: "Historical Fiction Award", year: 2018 }],
    booksWrittenIds: ["670015d5acba0ce3c21a3b1d"],
    bestAuthor: false,
    socialLinks: {
      twitter: "https://twitter.com/DavisMoore",
      facebook: "https://facebook.com/DavisMoore",
      website: "https://davismoore.com",
    },
    totalBooksSold: 450000,
    followers: [],
    isFeatured: false,
    authorQuotes: [
      "History is not just in the past, it lives in every word.",
      "Fiction brings the forgotten back to life.",
    ],
  },
  {
    name: "D.M. Narok",
    username: "d.m.narok",
    image: "https://randomuser.me/api/portraits/men/14.jpg",
    biography:
      "D.M. Narok is a fantasy author who builds worlds and weaves tales of magic and wonder.",
    birthDate: "1990-11-11",
    birthPlace: "Nairobi, Kenya",
    nationality: "Kenyan",
    famousWork: "The Last Magi",
    awards: [{ awardName: "Fantasy Worldbuilding Award", year: 2020 }],
    booksWrittenIds: ["670015d5acba0ce3c21a3b1e"],
    bestAuthor: false,
    socialLinks: {
      twitter: "https://twitter.com/DMNarok",
      facebook: "https://facebook.com/DMNarok",
      website: "https://dmnarok.com",
    },
    totalBooksSold: 370000,
    followers: [],
    isFeatured: false,
    authorQuotes: [
      "Magic is in the heart of every story.",
      "Imagination is the key to all worlds.",
    ],
  },
  {
    name: "Jen Congdon",
    username: "jencongdon",
    image: "https://randomuser.me/api/portraits/men/15.jpg",
    biography:
      "Jen Congdon, a romance novelist, writes heartfelt stories that resonate with readers everywhere.",
    birthDate: "1988-07-07",
    birthPlace: "Toronto, Canada",
    nationality: "Canadian",
    famousWork: "Hearts Entwined",
    awards: [{ awardName: "Best Romance Novel", year: 2021 }],
    booksWrittenIds: ["670015d5acba0ce3c21a3b1f"],
    bestAuthor: false,
    socialLinks: {
      twitter: "https://twitter.com/JenCongdon",
      facebook: "https://facebook.com/JenCongdon",
      website: "https://jencongdon.com",
    },
    totalBooksSold: 290000,
    followers: [],
    isFeatured: false,
    authorQuotes: [
      "Love is the greatest adventure of all.",
      "In every heart, there's a story waiting to be told.",
    ],
  },

  {
    name: "S.J. Lee",
    username: "s.j.lee",
    image: "https://randomuser.me/api/portraits/men/16.jpg",
    biography:
      "S.J. Lee is a rising star in the world of speculative fiction, blending science with philosophy in her thought-provoking novels.",
    birthDate: "1985-03-12",
    birthPlace: "Seoul, South Korea",
    nationality: "Korean",
    famousWork: "Beyond the Veil",
    awards: [{ awardName: "Speculative Fiction Award", year: 2020 }],
    booksWrittenIds: ["670015d5acba0ce3c21a3b20"],
    bestAuthor: false,
    socialLinks: {
      twitter: "https://twitter.com/SJLee",
      facebook: "https://facebook.com/SJLee",
      website: "https://sjlee.com",
    },
    totalBooksSold: 220000,
    followers: [],
    isFeatured: false,
    authorQuotes: [
      "In every question lies the seed of a new universe.",
      "Fiction is the art of asking 'what if.'",
    ],
  },
  {
    name: "Ferne Arfin",
    username: "fernearfin",
    image: "https://randomuser.me/api/portraits/men/17.jpg",
    biography:
      "Ferne Arfin writes literary fiction that explores the human condition, delving into complex emotions and relationships.",
    birthDate: "1968-05-09",
    birthPlace: "Sydney, Australia",
    nationality: "Australian",
    famousWork: "The Silent Sea",
    awards: [{ awardName: "Literary Fiction Prize", year: 2017 }],
    booksWrittenIds: ["670015d5acba0ce3c21a3b21"],
    bestAuthor: false,
    socialLinks: {
      twitter: "https://twitter.com/FerneArfin",
      facebook: "https://facebook.com/FerneArfin",
      website: "https://fernearfin.com",
    },
    totalBooksSold: 310000,
    followers: [],
    isFeatured: false,
    authorQuotes: [
      "Every story is a mirror reflecting a piece of the soul.",
      "The quietest moments often speak the loudest.",
    ],
  },
  {
    name: "Ashley Wall",
    username: "ashleywall",
    image: "https://randomuser.me/api/portraits/men/18.jpg",
    biography:
      "Ashley Wall is a beloved children's author who brings magic and wonder into the lives of young readers.",
    birthDate: "1991-08-25",
    birthPlace: "Manchester, UK",
    nationality: "British",
    famousWork: "The Enchanted Forest",
    awards: [{ awardName: "Children's Book of the Year", year: 2022 }],
    booksWrittenIds: ["670015d5acba0ce3c21a3b22"],
    bestAuthor: false,
    socialLinks: {
      twitter: "https://twitter.com/AshleyWall",
      facebook: "https://facebook.com/AshleyWall",
      website: "https://ashleywall.com",
    },
    totalBooksSold: 270000,
    followers: [],
    isFeatured: false,
    authorQuotes: [
      "Every child is a story waiting to unfold.",
      "The magic of childhood is in the pages we turn.",
    ],
  },
  {
    name: "Ben Sharafski",
    username: "bensharafski",
    image: "https://randomuser.me/api/portraits/men/19.jpg",
    biography:
      "Ben Sharafski writes gripping horror novels that keep readers awake at night, masterfully blending fear and suspense.",
    birthDate: "1983-12-01",
    birthPlace: "Warsaw, Poland",
    nationality: "Polish",
    famousWork: "The Haunting of Hill's End",
    awards: [{ awardName: "Horror Writer of the Year", year: 2019 }],
    booksWrittenIds: ["670015d5acba0ce3c21a3b23"],
    bestAuthor: false,
    socialLinks: {
      twitter: "https://twitter.com/BenSharafski",
      facebook: "https://facebook.com/BenSharafski",
      website: "https://bensharafski.com",
    },
    totalBooksSold: 350000,
    followers: [],
    isFeatured: false,
    authorQuotes: [
      "Fear is the darkest shadow of the unknown.",
      "Every monster tells a story.",
    ],
  },
  {
    name: "Sarah Gowayed",
    username: "sarahgowayed",
    image: "https://randomuser.me/api/portraits/men/20.jpg",
    biography:
      "Sarah Gowayed is a contemporary fiction author, telling the stories of modern-day relationships and societal challenges.",
    birthDate: "1986-11-04",
    birthPlace: "Cairo, Egypt",
    nationality: "Egyptian",
    famousWork: "Between Two Worlds",
    awards: [{ awardName: "Contemporary Fiction Award", year: 2021 }],
    booksWrittenIds: ["670015d5acba0ce3c21a3b24"],
    bestAuthor: false,
    socialLinks: {
      twitter: "https://twitter.com/SarahGowayed",
      facebook: "https://facebook.com/SarahGowayed",
      website: "https://sarahgowayed.com",
    },
    totalBooksSold: 230000,
    followers: [],
    isFeatured: false,
    authorQuotes: [
      "In every person lies an untold story.",
      "Fiction gives voice to the voiceless.",
    ],
  },

  {
    name: "Bill Sugrue",
    username: "billsugrue",
    image: "https://randomuser.me/api/portraits/men/21.jpg",
    biography:
      "Bill Sugrue is a prolific author of detective novels, captivating readers with complex plots and unforgettable characters.",
    birthDate: "1975-07-17",
    birthPlace: "Dublin, Ireland",
    nationality: "Irish",
    famousWork: "The Crimson Detective",
    awards: [{ awardName: "Best Crime Fiction", year: 2018 }],
    booksWrittenIds: ["670015d5acba0ce3c21a3b25"],
    bestAuthor: false,
    socialLinks: {
      twitter: "https://twitter.com/BillSugrue",
      facebook: "https://facebook.com/BillSugrue",
      website: "https://billsugrue.com",
    },
    totalBooksSold: 410000,
    followers: [],
    isFeatured: false,
    authorQuotes: [
      "Mystery is the art of misdirection.",
      "In every crime, there is a story waiting to be told.",
    ],
  },
  {
    name: "Lexi Rees",
    username: "lexirees",
    image: "https://randomuser.me/api/portraits/men/22.jpg",
    biography:
      "Lexi Rees is an award-winning romance novelist, creating heartwarming and emotional stories that resonate with readers worldwide.",
    birthDate: "1990-02-15",
    birthPlace: "Los Angeles, USA",
    nationality: "American",
    famousWork: "Love Across Oceans",
    awards: [{ awardName: "Romance Novel of the Year", year: 2019 }],
    booksWrittenIds: ["670015d5acba0ce3c21a3b26"],
    bestAuthor: false,
    socialLinks: {
      twitter: "https://twitter.com/LexiRees",
      facebook: "https://facebook.com/LexiRees",
      website: "https://lexirees.com",
    },
    totalBooksSold: 390000,
    followers: [],
    isFeatured: false,
    authorQuotes: [
      "Love is the most powerful story we can tell.",
      "Every heart has a journey worth sharing.",
    ],
  },
  {
    name: "Vladimir Stefan",
    username: "vladimirstefan",
    image: "https://randomuser.me/api/portraits/men/23.jpg",
    biography:
      "Vladimir Stefan is a historian turned author, specializing in historical fiction that brings the past to life with vivid detail.",
    birthDate: "1978-11-10",
    birthPlace: "Moscow, Russia",
    nationality: "Russian",
    famousWork: "The Fall of Empires",
    awards: [{ awardName: "Historical Fiction Award", year: 2020 }],
    booksWrittenIds: ["670015d5acba0ce3c21a3b27"],
    bestAuthor: false,
    socialLinks: {
      twitter: "https://twitter.com/VladimirStefan",
      facebook: "https://facebook.com/VladimirStefan",
      website: "https://vladimirstefan.com",
    },
    totalBooksSold: 460000,
    followers: [],
    isFeatured: false,
    authorQuotes: [
      "History is a tale retold by the victors and the vanquished.",
      "In every era, there is a lesson for today.",
    ],
  },
  {
    name: "Mitesh Desai",
    username: "miteshdesai",
    image: "https://randomuser.me/api/portraits/men/24.jpg",
    biography:
      "Mitesh Desai is an acclaimed motivational speaker and author, empowering readers to achieve their best lives through practical advice and wisdom.",
    birthDate: "1982-05-27",
    birthPlace: "Ahmedabad, India",
    nationality: "Indian",
    famousWork: "Unleash Your Potential",
    awards: [{ awardName: "Self-Help Book of the Year", year: 2021 }],
    booksWrittenIds: ["670015d5acba0ce3c21a3b28"],
    bestAuthor: false,
    socialLinks: {
      twitter: "https://twitter.com/MiteshDesai",
      facebook: "https://facebook.com/MiteshDesai",
      website: "https://miteshdesai.com",
    },
    totalBooksSold: 500000,
    followers: [],
    isFeatured: false,
    authorQuotes: [
      "Success begins in the mind.",
      "You are only one decision away from a different life.",
    ],
  },
  {
    name: "Shannon Damuth",
    username: "shannondamuth",
    image: "https://randomuser.me/api/portraits/men/25.jpg",
    biography:
      "Shannon Damuth is an environmental activist and author, using her platform to inspire change and awareness about global ecological issues.",
    birthDate: "1993-04-03",
    birthPlace: "Denver, USA",
    nationality: "American",
    famousWork: "The Last Rainforest",
    awards: [{ awardName: "Eco-Writer Award", year: 2020 }],
    booksWrittenIds: ["670015d5acba0ce3c21a3b29"],
    bestAuthor: false,
    socialLinks: {
      twitter: "https://twitter.com/ShannonDamuth",
      facebook: "https://facebook.com/ShannonDamuth",
      website: "https://shannondamuth.com",
    },
    totalBooksSold: 270000,
    followers: [],
    isFeatured: false,
    authorQuotes: [
      "We have one planet—it's time we start acting like it.",
      "Nature is not a resource; it's a treasure.",
    ],
  },
];
