export const books = [
  {
    BookName: "The Courage of Slackers",
    AuthorName: "Daniel Tiernan",
    authorId: "670817b00298ede071db1abe",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/210/large_72e8552c889132a5f95e5843bc60a2b9.jpg",
    Description:
      "The cover features a fictional but typical Minneapolis dive bar, grounding the story in a distinct aesthetic while hinting at key plot elements. The 'Art Deco' style, common to Minneapolis bars, influenced both the cover design and the font. It worked well for a modern minimalist design: it's readabile at small scales while remaining interesting up close. Details like the main character, a lurking figure, broken glass, and a cat stalking a pigeon on the roof add suspenseful hints to the story.",
    PublicationName: "Urban Tales Publishing",
    PublicationId: "",
    PublishDate: "2022-05-14",
    Price: 15.99,
    Genre: "Fiction, Drama",
    wishList: [],
    readList: [],
  },
  {
    BookName: "WORM$",
    AuthorName: "Khari Gordon",
    authorId: "670817b00298ede071db1abf",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/209/large_9a7204fefedb8bf558ae93108b5799c6.jpg",
    Description:
      "The cover is directly inspired by the plot, aiming to capture the intense sense of action and adventure. It embraces an underground vibe, signalling to the audience that they’re in for a wild, unpredictable ride filled with eccentric twists. The bold typography and edgy illustration style were carefully chosen to reflect the chaotic energy of the story, letting readers know they’re about to dive into something thrilling and out of the ordinary.",
    PublicationName: "Underground Press",
    PublicationId: "",
    PublishDate: "2021-10-10",
    Price: 13.5,
    Genre: "Science Fiction, Adventure",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Knot by Knot",
    AuthorName: "Davis Moore",
    authorId: "670817b00298ede071db1ac0",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/205/large_4283954692b297c2b5c45aa2c1d6f7a2.jpg",
    Description:
      "The book explores how the good news of Jesus helps readers untangle the knots of sin and addiction. The hand, inspired by ancient Christian iconography, symbolizes God's hand, while the background texture comes from historic art archives. The colors and illustration are on-trend with Christian self-help books, but the ancient elements add uniqueness. I love incorporating Christian symbolism and artwork to connect modern readers to the rich history of the church and the timeless Gospel message.",
    PublicationName: "Faith & Light Publications",
    PublicationId: "",
    PublishDate: "2020-08-22",
    Price: 17.99,
    Genre: "Non-Fiction, Religion",
    wishList: [],
    readList: [],
  },
  {
    BookName: "The Countryside Orphanage",
    AuthorName: "D.M. Narok",
    authorId: "670817b00298ede071db1ac1",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/204/large_1247539007cd95191f62749e53083655.jpg",
    Description:
      "The author wanted me to convey a complicated suspense/thriller story in a simple, elegant way — one that evoked a mood rather than telegraphed the plot line. That directive suited my style perfectly, because I tend to prefer captivating, moody images that draw the eye while offering subtle hints of what lies within. I feel like this has both a contemporary yet classic look; one that will look fresh ten years from now as it does today.",
    PublicationName: "Mystery House",
    PublicationId: "",
    PublishDate: "2023-03-17",
    Price: 19.25,
    Genre: "Thriller, Suspense",
    wishList: [],
    readList: [],
  },
  {
    BookName: "A Good Day For A Hike",
    AuthorName: "Jen Congdon",
    authorId: "670817b00298ede071db1ac2",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/201/large_cd1a2490cec9107538e12c565fa90b3e.jpg",
    Description:
      "For this cover, I chose a classic serif font that remained easy to read without overpowering the playful artwork. This clean, readable typography complements the joyful illustrations, achieving a harmonious balance between visual charm and timeless design. The result is a cover that feels both fresh and classic, appealing to young readers while maintaining a sophisticated, enduring look.",
    PublicationName: "Green Trails Publishing",
    PublicationId: "",
    PublishDate: "2022-07-05",
    Price: 12.99,
    Genre: "Non-Fiction, Travel",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Of Friction",
    AuthorName: "S.J. Lee",
    authorId: "670817b00298ede071db1ac3",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/192/large_e9b61e3f8f9f151825a06efe11af85d8.jpg",
    Description:
      "The priority was to create a consistent series look across all three books, focusing on the protagonist's arm transformation as the story progresses. S.J. prefers minimalist compositions and wanted to pay homage to the Southern Reach series, which was a big influence. We used a gridded title treatment and a textured background interacting with the protagonist's hand, tied to the book's events. These core elements will be carried through the entire series.",
    PublicationName: "Redmark Chronicles",
    PublicationId: "",
    PublishDate: "2021-11-29",
    Price: 14.75,
    Genre: "Fantasy, Science Fiction",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Tunnel of Mirrors",
    AuthorName: "Ferne Arfin",
    authorId: "670817b00298ede071db1ac4",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/189/large_11787f4cd285774a4c8d8a1c098d5d7d.jpg",
    Description:
      "It was important that this beautiful novel have a beautiful, romantic cover without being trite. The story takes place in the 1900s and is about a young woman coming to New York from Ireland. The ocean is a big part of the story in various ways. The gull flying away from the other birds was inspired by the main character, a very independent, unique young woman. I wanted to add some interest by having the title look like it's sinking into the sea and being reflected like a mirror.",
    PublicationName: "Oceanic Press",
    PublicationId: "",
    PublishDate: "2019-12-05",
    Price: 16.99,
    Genre: "Romance, Drama",
    wishList: [],
    readList: [],
  },
  {
    BookName: "The Day I Had a Dinosaur",
    AuthorName: "Ashley Wall",
    authorId: "670817b00298ede071db1ac5",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/188/large_ba0c7956751de1f8ddf5b48149a5156f.jpg",
    Description:
      "The picture book captures children imagining themselves playing with large construction vehicles, like bulldozers. The cover features the main character enjoying a bulldozer, creating an exciting visual that hints at the fun story inside. With the trend of strong characters on covers, especially for small online thumbnails, I focused on using bold colors and a clean design. Strong illustrations and text design were emphasized to ensure the cover stands out and reflects the story.",
    PublicationName: "Little Learners",
    PublicationId: "",
    PublishDate: "2022-09-12",
    Price: 9.99,
    Genre: "Children's, Picture Book",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Returning to Carthage",
    AuthorName: "Ben Sharafski",
    authorId: "670817b00298ede071db1ac6",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/186/large_0b5779f4ef3d8c3ec286769d41f3c619.jpg",
    Description:
      "For this short story collection, I aimed to evoke a sense of place and atmosphere without focusing on a specific narrative. The fig tree and Lorikeet, featured in multiple stories, serve as a tonal and geographical anchor. While botanical and avian illustrations are popular, I chose a less patterned approach with a mix of delicate and saturated colors. Starting with a subdued palette, I added rich, vibrant hues to bring the cover to life and reflect the warmth of the stories.",
    PublicationName: "Carthage Collective",
    PublicationId: "",
    PublishDate: "2021-02-18",
    Price: 18.5,
    Genre: "Short Stories, Fiction",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Samah The Seed",
    AuthorName: "Sarah Gowayed",
    authorId: "670817b00298ede071db1ac7",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/182/large_fc87ae9b24a402ab642fb02736eb0144.png",
    Description:
      "In the cover for Samah the Seed, I wanted to create a richness of colour and the feeling of closeness that Samah has with her Baba. It was important to convey the underlying theme of spirituality without being too specific, so the glowing light coming from the top right was added to reference God in a way that all readers could relate to. The book title was hand drawn so that it could appear to be connected to the plant and further reiterate the growth for Samah throughout the book.",
    PublicationName: "Spiritual Garden Publishing",
    PublicationId: "",
    PublishDate: "2020-06-09",
    Price: 11.99,
    Genre: "Children's, Spiritual",
    wishList: [],
    readList: [],
  },
  {
    BookName: "It Ate One Hundred",
    AuthorName: "Bill Sugrue",
    authorId: "670817b00298ede071db1ac8",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/180/large_9ce935fb391ef9cde19a26ef8a9561a1.jpg",
    Description:
      "The cover illustration plays with the book's title, inviting the audience to initially think the story revolves around a 'big cat who ate one hundred.' However, the true essence lies deeper: the artwork symbolizes the harsh realities of survival in the wilderness, where unseen dangers lurk in every shadow. The aim was to evoke a sense of displacement, drawing the audience into the experience of being far from home and confronted with the vast unknown.",
    PublicationName: "Survival Instinct Publishing",
    PublicationId: "",
    PublishDate: "2023-04-03",
    Price: 16.75,
    Genre: "Fantasy, Adventure",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Eternal Seas (The Relic Hunters)",
    AuthorName: "Lexi Rees",
    authorId: "670817b00298ede071db1ac9",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/178/large_6ea9129e49eb8d1a4fd001e8b4a292f6.jpg",
    Description:
      "We aimed to convey adventure, danger, and establish a fantasy world with young heroes. Middle-grade stories often use detailed, figurative illustrations, but I suggested a more graphic style inspired by cut paper. The colors are strikingly powerful and they are rarely used in this book category. The logo stands out beautifully, even as a thumbnail. Despite the amount of information depicted, the image remains very easy to read.",
    PublicationName: "Adventure Ink",
    PublicationId: "",
    PublishDate: "2022-01-27",
    Price: 14.99,
    Genre: "Fantasy, Adventure",
    wishList: [],
    readList: [],
  },
  {
    BookName: "What to Eat During the Apocalypse",
    AuthorName: "Vladimir Stefan",
    authorId: "670817b00298ede071db1aca",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/177/large_2f64ac228f6cd440cfc798f47fa17b95.jpg",
    Description:
      "This design highlights the quirky, funny title—dystopian recipes!—while presenting the dark backdrop in an engaging way. We chose a gas-mask-wearing chef to capture the book's strange spirit. Borrowing market trends like simple, solid colors and an illustrative style appealing on social media, we created a timeless look. The distressed sans serif typography is readable and suggests breakdown. We aimed for a design that lets the clever title shine.",
    PublicationName: "End Times Kitchen",
    PublicationId: "",
    PublishDate: "2023-08-22",
    Price: 13.99,
    Genre: "Non-Fiction, Humor",
    wishList: [],
    readList: [],
  },
  {
    BookName: "The Big Shot Trader",
    AuthorName: "Mitesh Desai",
    authorId: "670817b00298ede071db1acb",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/171/large_7e4460ab3c5ca4b763328353646ebea2.jpg",
    Description:
      "The Big Shot Trader is all about evolving in a highly competitive, stressful industry. The idea was to use a slightly over-the-top composition to emphasize the 'clog in the machine' feeling of the main character. Balancing an overwhelming corporate blue with vibrant yellow details helped the cover stand out without losing the familiarity of current market trends. Incorporating the title into the decor is often a great way to make a design truly unique.",
    PublicationName: "Market Edge Publishing",
    PublicationId: "",
    PublishDate: "2021-05-30",
    Price: 17.5,
    Genre: "Non-Fiction, Finance",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Question Mark: The Freshman Experience",
    AuthorName: "Shannon Damuth",
    authorId: "670817b00298ede071db1acc",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/170/large_c59c15221efd0fa2c84916dd5c296ce3.jpg",
    Description:
      "The book's short stories and Shannon's love for poetic writing called for a simple, artistic typographical approach. I researched market trends from top publishers and authors to align with the market while still standing out. The focus was on originality in concept, icon design, typography, and styling.",
    PublicationName: "Dorm Life Chronicles",
    PublicationId: "",
    PublishDate: "2020-11-12",
    Price: 12.99,
    Genre: "Fiction, Young Adult",
    wishList: [],
    readList: [],
  },
  {
    BookName: "A Blackened Bond",
    AuthorName: "Isla DavonIsla Davon",
    authorId: "",
    CoverImage: "	https://m.media-amazon.com/images/I/71N8qIrz7IL._SY522_.jpg",
    Description:
      "A Blackened Bond is the second book of The Blackened Blade series, and a paranormal why choose romance. It’s full of action, revenge and five dark and damaged love interests that the FMC will not have to choose between. It contains adult themes and bad-language throughout which some readers may find upsetting..",
    PublicationName: "Kindle Unlimited",
    PublicationId: "",
    PublishDate: "2024-9-30",
    Price: 4.99,
    Genre: "Fiction, Fantasy",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Karla's Choice: A John le Carré Novel",
    AuthorName: "Nick HarkawayNick Harkaway",
    authorId: "",
    CoverImage: "https://m.media-amazon.com/images/I/71KAnnYkStL._SY522_.jpg",
    Description:
      "It is spring in 1963 and George Smiley has left the Circus. With the wreckage of the West’s spy war against the Soviets strewn across Europe, he has eyes only for a more peaceful life. And indeed, with his marriage more secure than ever, there is a rumor that George Smiley might almost be happy.",
    PublicationName: "Penguin Group",
    PublicationId: "",
    PublishDate: "2024-9-22",
    Price: 7.47,
    Genre: "Fiction, Science Fiction",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Pathfinder: First Colony Book 17",
    AuthorName: "Ken LozitoKen Lozito",
    authorId: "",
    CoverImage: "	https://m.media-amazon.com/images/I/81GlUvRO6LL._SY522_.jpg",
    Description:
      "Pathfinder is the 17th book in the bestselling military science fiction series, First Colony. Read the 17th book in this sprawling space opera today!",
    PublicationName: "Kindle Unlimited",
    PublicationId: "",
    PublishDate: "2024-9-25",
    Price: 5.99,
    Genre: "Fiction, Science Fiction",
    wishList: [],
    readList: [],
  },
  {
    BookName: "The Cinnamon Bun Book Store",
    AuthorName: "Laurie GilmoreLaurie Gilmore",
    authorId: "",
    CoverImage: "https://m.media-amazon.com/images/I/81ZLJHbfHkL._SY522_.jpg",
    Description:
      "When a secret message turns up hidden in a book in the Cinnamon Bun Bookstore, Hazel can't understand it. As more secret codes appear between the pages, she decides to follow the trail of clues… she just needs someone to help her out.",
    PublicationName: "One More Chapter",
    PublicationId: "",
    PublishDate: "2024-8-29",
    Price: 2.99,
    Genre: "Suspense,Thriller",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Grave Matter: A Dark Gothic Romance Psych Thriller",
    AuthorName: "Karina HalleKarina Halle",
    authorId: "",
    CoverImage: "https://m.media-amazon.com/images/I/81ssKBtPqVL._SY522_.jpg",
    Description:
      "Horror Romance meets Science Fiction in this dark and delicious gothic psychological thriller by NYT bestseller Karina Halle, perfect for fans of Gothikana, Ninth House, and Mexican Gothic.",
    PublicationName: "Kindle Unlimited",
    PublicationId: "",
    PublishDate: "2024-8-21",
    Price: 4.99,
    Genre: "Suspense,Thriller",
    wishList: [],
    readList: [],
  },
  {
    BookName: "The Mistletoe Mystery: A Maid Novella (Molly the Maid)",
    AuthorName: "Nita ProseNita Prose",
    authorId: "",
    CoverImage: "https://m.media-amazon.com/images/I/81ssKBtPqVL._SY522_.jpg",
    Description:
      "Molly Gray has always loved the holidays. When Molly was a child, her gran went to great lengths to make the season merry and bright, full of cherished traditions. The first few Christmases without Gran were hard on Molly, but this year, her beloved boyfriend and fellow festive spirit, Juan Manuel, is intent on making the season Molly’s mofinst joyful yet.",
    PublicationName: "Ballantine Books",
    PublicationId: "",
    PublishDate: "2024-8-1",
    Price: 4.99,
    Genre: "Suspense,Thriller",
    wishList: [],
    readList: [],
  },
  {
    BookName: "The Mistletoe Mystery: A Maid Novella (Molly the Maid)",
    AuthorName: "Nita ProseNita Prose",
    authorId: "",
    CoverImage: "https://m.media-amazon.com/images/I/71gR1dW+Y5L._SY522_.jpg",
    Description:
      "Molly Gray has always loved the holidays. When Molly was a child, her gran went to great lengths to make the season merry and bright, full of cherished traditions. The first few Christmases without Gran were hard on Molly, but this year, her beloved boyfriend and fellow festive spirit, Juan Manuel, is intent on making the season Molly’s mofinst joyful yet.",
    PublicationName: "Ballantine Books",
    PublicationId: "",
    PublishDate: "2024-8-1",
    Price: 4.99,
    Genre: "Suspense,Thriller",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Death at the Sign of the Rook: A Jackson Brodie",
    AuthorName: "Kate AtkinsonKate Atkinson",
    authorId: "",
    CoverImage: "https://m.media-amazon.com/images/I/81MqvWBVSRL._SY522_.jpg",
    Description:
      "How delicious to have Jackson Brodie back, this time in a story that starts off in Agatha Christie's world but soon becomes a landscape that could only have been crafted from the pen of the incomparable Kate Atkinson.”–Ian Rankin, author of the Inspector Rebus Novels",
    PublicationName: "Doubleday",
    PublicationId: "",
    PublishDate: "2024-8-3",
    Price: 21.61,
    Genre: "Suspense,Thriller",
    wishList: [],
    readList: [],
  },
  {
    BookName: "A Day in the Life of a Witch: Paranormal Women's Fiction ",
    AuthorName: "Brenda TrimBrenda Trim",
    authorId: "",
    CoverImage: "https://m.media-amazon.com/images/I/91wobu0DGsL._SY522_.jpg",
    Description:
      "Despite the uncertainty in my relationship with Spencer, he agrees to help me uncover who drugged me, and a startling revelation from a consultation with my deceased mother provides a crucial clue.",
    PublicationName: "Kindle Unlimited",
    PublicationId: "",
    PublishDate: "2024-8-15",
    Price: 2.99,
    Genre: "Suspense,Thriller",
    wishList: [],
    readList: [],
  },
  {
    BookName: "A Dark and Rising Tide",
    AuthorName: "Debra CastanedaDebra Castaneda",
    authorId: "",
    CoverImage: "https://m.media-amazon.com/images/I/81WpOda5fOL._SY522_.jpg",
    Description:
      "When a massive storm surge hits the central coast of California, the ferocious surf destroys buildings, floods streets, and washes up something sinister from the depths of the Monterey Bay.",
    PublicationName: "Kindle Unlimited",
    PublicationId: "",
    PublishDate: "2024-8-18",
    Price: 2.99,
    Genre: "Fantasy, Science Fiction",
    wishList: [],
    readList: [],
  },
  {
    BookName: "American Elsewhere",
    AuthorName: "Robert Jackson BennettRobert Jackson B…",
    authorId: "",
    CoverImage: "https://m.media-amazon.com/images/I/81WpOda5fOL._SY522_.jpg",
    Description:
      "When a massive storm surge hits the central coast of California, the ferocious surf destroys buildings, floods streets, and washes up something sinister from the depths of the Monterey Bay.",
    PublicationName: "Orbit",
    PublicationId: "",
    PublishDate: "2013-2-12",
    Price: 7.49,
    Genre: "Fantasy, Science Fiction",
    wishList: [],
    readList: [],
  },
  {
    BookName: "The Lost Library",
    AuthorName: " Rebecca Stead, Wendy Mass",
    authorId: "",
    CoverImage:
      "	https://prodimage.images-bn.com/pimages/2940178417003_p0_v3_s600x595.jpg",
    Description:
      "When a mysterious little free library (guarded by a large orange cat) appears overnight in the small town of Martinville, eleven-year-old Evan plucks two weathered books.",
    PublicationName: "Square Fish",
    PublicationId: "",
    PublishDate: "2025-2-25",
    Price: 8.99,
    Genre: "Children's, Picture Book",
    wishList: [],
    readList: [],
  },
  {
    BookName: "A Royal Conundrum (The Misfits #1)",
    AuthorName: "Lisa Yee",
    authorId: "",
    CoverImage:
      "https://prodimage.images-bn.com/pimages/2940159286512_p0_v3_s600x595.jpg",
    Description:
      "When a notorious thief is out for priceless treasure (gems! cats! general decorum!)-who're you gonna call? An elite team of crime-fighting underdogs, that's who! The Misfits are on the case in this hilarious series from Newbery Honoree Lisa Yee!",
    PublicationName: "Penguin Random House",
    PublicationId: "",
    PublishDate: "2024-1-1",
    Price: 16.2,
    Genre: "Children's, Picture Book",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Faker",
    AuthorName: "Gordon Korman",
    authorId: "",
    CoverImage:
      "https://prodimage.images-bn.com/pimages/2940191414225_p0_v2_s600x595.jpg",
    Description:
      "Trey knows how the trick works: His dad gets him into a school full of kids with rich parents. Trey makes friends, and his dad makes connections. Soon, there's the con, where Trey's dad suckers the other parents into giving him money for one of his schemes.",
    PublicationName: "Recorded Books",
    PublicationId: "",
    PublishDate: "2024-7-2",
    Price: 15.99,
    Genre: "Children's, Picture Book",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Rare Birds",
    AuthorName: " Jeff Miller",
    authorId: "",
    CoverImage:
      "	https://prodimage.images-bn.com/pimages/2940159879318_p0_v1_s600x595.jpg",
    Description:
      "Twelve-year-old Graham Dodds is no stranger to hospital waiting rooms. Sometimes, he feels like his entire life is one big waiting room. Waiting for the next doctor to tell them what's wrong with his mom. Waiting to find out what city they're moving to next. Waiting to see if they will finally get their miracle-a heart transplant to save his mom's life.",
    PublicationName: "Union Square Kids",
    PublicationId: "",
    PublishDate: "2023-1-31",
    Price: 16.99,
    Genre: "Children's, Picture Book",
    wishList: [],
    readList: [],
  },
  {
    BookName: "They Call Me No Sam!",
    AuthorName: "Drew Daywalt",
    authorId: "",
    CoverImage:
      "https://prodimage.images-bn.com/pimages/2940160590622_p0_v3_s600x595.jpg",
    Description:
      "When scientists Elaine and Gary Peterson adopt Sam to keep their son, Justin, company in the midst of a top-secret research project, they never imagine the precocious pup will cause more harm than good. But from chewing up Elaine's hair dryer (the “brain-melting heat cannon”) to his inability to be house-trained (who could resist the “pooping rug”?),",
    PublicationName: "HarperCollins",
    PublicationId: "",
    PublishDate: "2024-6-4",
    Price: 15.99,
    Genre: "Children's, Picture Book",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Grimstone: A Romantic Thriller",
    AuthorName: "Sophie LarkSophie Lark",
    authorId: "",
    CoverImage: "	https://m.media-amazon.com/images/I/81MrnvTqSxL._SY522_.jpg",
    Description:
      "Remi Hayes is beginning to think she's cursed―her fiancé cheated on her, her brother Jude is a major pain in her ass, and the moldering mansion she inherited from her uncle might just be haunted.Flipping Blackleaf Manor already feels impossible, even before Remi is blackmailed by Dane Covett, the dangerously hot doctor-next-door, and Grimstone's most eligible bachelor―if you can ignore the fact that everyone in town thinks he murdered his wife.",
    PublicationName: "Bloom Books",
    PublicationId: "",
    PublishDate: "2024-9-17",
    Price: 16.99,
    Genre: "Romance, Drama",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Stolen Touches: An Arranged Marriage Mafia Romance",
    AuthorName: "Neva AltajNeva Altaj",
    authorId: "",
    CoverImage: "https://m.media-amazon.com/images/I/91Jwt08Gt1L._SY522_.jpg",
    Description:
      "This is the fifth book in Perfectly Imperfect mafia series. Each book in this series features a different couple and can be read as a standalone, but for maximum enjoyment, follow the recommended reading order",
    PublicationName: "Neva Altaj ",
    PublicationId: "",
    PublishDate: "2024-8-12",
    Price: 14.99,
    Genre: "Romance, Drama",
    wishList: [],
    readList: [],
  },
  {
    BookName: "When He Takes: A Dark Mafia Romance ",
    AuthorName: "Gabrielle SandsGabrielle Sands",
    authorId: "",
    CoverImage: "https://m.media-amazon.com/images/I/810BTp07a5L._SY522_.jpg",
    Description:
      "I've fallen for a monster. A man who doesn't ask for what he wants—he takes. And now, he's taken me.Rowan Miller isn’t who I thought he was. He's Nero De Luca, the ex-consigliere of a notorious New York mob family, and he's been lying to me from the moment we met.",
    PublicationName: "Neva Altaj ",
    PublicationId: "",
    PublishDate: "2024-5-18",
    Price: 14.99,
    Genre: "Romance, Drama",
    wishList: [],
    readList: [],
  },
];
