export const books = [
  {
    BookName: "The Courage of Slackers",
    AuthorName: "Daniel Tiernan",
    AuthorUsername: "danieltiernan",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/210/large_72e8552c889132a5f95e5843bc60a2b9.jpg",
    Description:
      "The cover features a fictional but typical Minneapolis dive bar, grounding the story in a distinct aesthetic while hinting at key plot elements. The 'Art Deco' style, common to Minneapolis bars, influenced both the cover design and the font. It worked well for a modern minimalist design: it's readabile at small scales while remaining interesting up close. Details like the main character, a lurking figure, broken glass, and a cat stalking a pigeon on the roof add suspenseful hints to the story.",
    PublicationName: "Urban Tales Publishing",
    PublicationId: "",
    PublishDate: "2022-05-14",
    Price: 15.99,
    Rating: 4.5,
    Genre: "Fiction, Drama",
    wishList: [],
    readList: [],
  },
  {
    BookName: "WORM$",
    AuthorName: "Khari Gordon",
    AuthorUsername: "kharigordon",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/209/large_9a7204fefedb8bf558ae93108b5799c6.jpg",
    Description:
      "The cover is directly inspired by the plot, aiming to capture the intense sense of action and adventure. It embraces an underground vibe, signalling to the audience that they’re in for a wild, unpredictable ride filled with eccentric twists. The bold typography and edgy illustration style were carefully chosen to reflect the chaotic energy of the story, letting readers know they’re about to dive into something thrilling and out of the ordinary.",
    PublicationName: "Underground Press",
    PublicationId: "",
    PublishDate: "2021-10-10",
    Price: 13.5,
    Rating: 4.3,
    Genre: "Science Fiction, Adventure",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Knot by Knot",
    AuthorName: "Davis Moore",
    AuthorUsername: "davismoore",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/205/large_4283954692b297c2b5c45aa2c1d6f7a2.jpg",
    Description:
      "The book explores how the good news of Jesus helps readers untangle the knots of sin and addiction. The hand, inspired by ancient Christian iconography, symbolizes God's hand, while the background texture comes from historic art archives. The colors and illustration are on-trend with Christian self-help books, but the ancient elements add uniqueness. I love incorporating Christian symbolism and artwork to connect modern readers to the rich history of the church and the timeless Gospel message.",
    PublicationName: "Faith & Light Publications",
    PublicationId: "",
    PublishDate: "2020-08-22",
    Price: 17.99,
    Rating: 4.7,
    Genre: "Non-Fiction, Religion",
    wishList: [],
    readList: [],
  },
  {
    BookName: "The Countryside Orphanage",
    AuthorName: "D.M. Narok",
    AuthorUsername: "d.m.narok",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/204/large_1247539007cd95191f62749e53083655.jpg",
    Description:
      "The author wanted me to convey a complicated suspense/thriller story in a simple, elegant way — one that evoked a mood rather than telegraphed the plot line. That directive suited my style perfectly, because I tend to prefer captivating, moody images that draw the eye while offering subtle hints of what lies within. I feel like this has both a contemporary yet classic look; one that will look fresh ten years from now as it does today.",
    PublicationName: "Mystery House",
    PublicationId: "",
    PublishDate: "2023-03-17",
    Price: 19.25,
    Rating: 4.6,
    Genre: "Thriller, Suspense",
    wishList: [],
    readList: [],
  },
  {
    BookName: "A Good Day For A Hike",
    AuthorName: "Jen Congdon",
    AuthorUsername: "jencongdon",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/201/large_cd1a2490cec9107538e12c565fa90b3e.jpg",
    Description:
      "For this cover, I chose a classic serif font that remained easy to read without overpowering the playful artwork. This clean, readable typography complements the joyful illustrations, achieving a harmonious balance between visual charm and timeless design. The result is a cover that feels both fresh and classic, appealing to young readers while maintaining a sophisticated, enduring look.",
    PublicationName: "Green Trails Publishing",
    PublicationId: "",
    PublishDate: "2022-07-05",
    Price: 12.99,
    Rating: 4.4,
    Genre: "Non-Fiction, Travel",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Of Friction",
    AuthorName: "S.J. Lee",
    AuthorUsername: "s.j.lee",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/192/large_e9b61e3f8f9f151825a06efe11af85d8.jpg",
    Description:
      "The priority was to create a consistent series look across all three books, focusing on the protagonist's arm transformation as the story progresses. S.J. prefers minimalist compositions and wanted to pay homage to the Southern Reach series, which was a big influence. We used a gridded title treatment and a textured background interacting with the protagonist's hand, tied to the book's events. These core elements will be carried through the entire series.",
    PublicationName: "Redmark Chronicles",
    PublicationId: "",
    PublishDate: "2021-11-29",
    Price: 14.75,
    Rating: 4.2,
    Genre: "Fantasy, Science Fiction",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Tunnel of Mirrors",
    AuthorName: "Ferne Arfin",
    AuthorUsername: "fernearfin",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/189/large_11787f4cd285774a4c8d8a1c098d5d7d.jpg",
    Description:
      "It was important that this beautiful novel have a beautiful, romantic cover without being trite. The story takes place in the 1900s and is about a young woman coming to New York from Ireland. The ocean is a big part of the story in various ways. The gull flying away from the other birds was inspired by the main character, a very independent, unique young woman. I wanted to add some interest by having the title look like it's sinking into the sea and being reflected like a mirror.",
    PublicationName: "Oceanic Press",
    PublicationId: "",
    PublishDate: "2019-12-05",
    Price: 16.99,
    Rating: 4.8,
    Genre: "Romance, Drama",
    wishList: [],
    readList: [],
  },
  {
    BookName: "The Day I Had a Dinosaur",
    AuthorName: "Ashley Wall",
    AuthorUsername: "ashleywall",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/188/large_ba0c7956751de1f8ddf5b48149a5156f.jpg",
    Description:
      "The picture book captures children imagining themselves playing with large construction vehicles, like bulldozers. The cover features the main character enjoying a bulldozer, creating an exciting visual that hints at the fun story inside. With the trend of strong characters on covers, especially for small online thumbnails, I focused on using bold colors and a clean design. Strong illustrations and text design were emphasized to ensure the cover stands out and reflects the story.",
    PublicationName: "Little Learners",
    PublicationId: "",
    PublishDate: "2022-09-12",
    Price: 9.99,
    Rating: 4.1,
    Genre: "Children's, Picture Book",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Returning to Carthage",
    AuthorName: "Ben Sharafski",
    AuthorUsername: "bensharafski",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/186/large_0b5779f4ef3d8c3ec286769d41f3c619.jpg",
    Description:
      "For this short story collection, I aimed to evoke a sense of place and atmosphere without focusing on a specific narrative. The fig tree and Lorikeet, featured in multiple stories, serve as a tonal and geographical anchor. While botanical and avian illustrations are popular, I chose a less patterned approach with a mix of delicate and saturated colors. Starting with a subdued palette, I added rich, vibrant hues to bring the cover to life and reflect the warmth of the stories.",
    PublicationName: "Carthage Collective",
    PublicationId: "",
    PublishDate: "2021-02-18",
    Price: 18.5,
    Rating: 4.5,
    Genre: "Short Stories, Fiction",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Samah The Seed",
    AuthorName: "Sarah Gowayed",
    AuthorUsername: "sarahgowayed",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/182/large_fc87ae9b24a402ab642fb02736eb0144.png",
    Description:
      "In the cover for Samah the Seed, I wanted to create a richness of colour and the feeling of closeness that Samah has with her Baba. It was important to convey the underlying theme of spirituality without being too specific, so the glowing light coming from the top right was added to reference God in a way that all readers could relate to. The book title was hand drawn so that it could appear to be connected to the plant and further reiterate the growth for Samah throughout the book.",
    PublicationName: "Spiritual Garden Publishing",
    PublicationId: "",
    PublishDate: "2020-06-09",
    Price: 11.99,
    Rating: 4.7,
    Genre: "Children's, Spiritual",
    wishList: [],
    readList: [],
  },
  {
    BookName: "It Ate One Hundred",
    AuthorName: "Bill Sugrue",
    AuthorUsername: "billsugrue",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/180/large_9ce935fb391ef9cde19a26ef8a9561a1.jpg",
    Description:
      "The cover illustration plays with the book's title, inviting the audience to initially think the story revolves around a 'big cat who ate one hundred.' However, the true essence lies deeper: the artwork symbolizes the harsh realities of survival in the wilderness, where unseen dangers lurk in every shadow. The aim was to evoke a sense of displacement, drawing the audience into the experience of being far from home and confronted with the vast unknown.",
    PublicationName: "Survival Instinct Publishing",
    PublicationId: "",
    PublishDate: "2023-04-03",
    Price: 16.75,
    Rating: 4.3,
    Genre: "Fantasy, Adventure",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Eternal Seas (The Relic Hunters)",
    AuthorName: "Lexi Rees",
    AuthorUsername: "lexirees",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/178/large_6ea9129e49eb8d1a4fd001e8b4a292f6.jpg",
    Description:
      "We aimed to convey adventure, danger, and establish a fantasy world with young heroes. Middle-grade stories often use detailed, figurative illustrations, but I suggested a more graphic style inspired by cut paper. The colors are strikingly powerful and they are rarely used in this book category. The logo stands out beautifully, even as a thumbnail. Despite the amount of information depicted, the image remains very easy to read.",
    PublicationName: "Adventure Ink",
    PublicationId: "",
    PublishDate: "2022-01-27",
    Price: 14.99,
    Rating: 4.6,
    Genre: "Fantasy, Adventure",
    wishList: [],
    readList: [],
  },
  {
    BookName: "What to Eat During the Apocalypse",
    AuthorName: "Vladimir Stefan",
    AuthorUsername: "vladimirstefan",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/177/large_2f64ac228f6cd440cfc798f47fa17b95.jpg",
    Description:
      "This design highlights the quirky, funny title—dystopian recipes!—while presenting the dark backdrop in an engaging way. We chose a gas-mask-wearing chef to capture the book's strange spirit. Borrowing market trends like simple, solid colors and an illustrative style appealing on social media, we created a timeless look. The distressed sans serif typography is readable and suggests breakdown. We aimed for a design that lets the clever title shine.",
    PublicationName: "End Times Kitchen",
    PublicationId: "",
    PublishDate: "2023-08-22",
    Price: 13.99,
    Rating: 4.4,
    Genre: "Non-Fiction, Humor",
    wishList: [],
    readList: [],
  },
  {
    BookName: "The Big Shot Trader",
    AuthorName: "Mitesh Desai",
    AuthorUsername: "miteshdesai",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/171/large_7e4460ab3c5ca4b763328353646ebea2.jpg",
    Description:
      "The Big Shot Trader is all about evolving in a highly competitive, stressful industry. The idea was to use a slightly over-the-top composition to emphasize the 'clog in the machine' feeling of the main character. Balancing an overwhelming corporate blue with vibrant yellow details helped the cover stand out without losing the familiarity of current market trends. Incorporating the title into the decor is often a great way to make a design truly unique.",
    PublicationName: "Market Edge Publishing",
    PublicationId: "",
    PublishDate: "2021-05-30",
    Price: 17.5,
    Rating: 4.5,
    Genre: "Non-Fiction, Finance",
    wishList: [],
    readList: [],
  },
  {
    BookName: "Question Mark: The Freshman Experience",
    AuthorName: "Shannon Damuth",
    AuthorUsername: "shannondamuth",
    CoverImage:
      "https://blog-cdn.reedsy.com/directories/gallery/170/large_c59c15221efd0fa2c84916dd5c296ce3.jpg",
    Description:
      "The book's short stories and Shannon's love for poetic writing called for a simple, artistic typographical approach. I researched market trends from top publishers and authors to align with the market while still standing out. The focus was on originality in concept, icon design, typography, and styling.",
    PublicationName: "Dorm Life Chronicles",
    PublicationId: "",
    PublishDate: "2020-11-12",
    Price: 12.99,
    Rating: 4.1,
    Genre: "Fiction, Young Adult",
    wishList: [],
    readList: [],
  },
];
